development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://iicdrikocaykpu:bLvr2vW_nbbTa3HWKWVwtbc2iF@ec2-204-236-228-133.compute-1.amazonaws.com:5432/d9pcks5t03ta7t
